// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PrestaToSap.model.Context;

#nullable disable

namespace PrestaToSap.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("PrestaToSap.model.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CRNDeliveryNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CRNInvoiceNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CarrierTaxRate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ConversionRate")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentState")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateAdd")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateUpd")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DeliveryDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("DeliveryNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Gift")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GiftMessage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("IdAddressDelivery")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdAddressInvoice")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdCarrier")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdCart")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdCurrency")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdCustomer")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdLang")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdShop")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdShopGroup")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MobileTheme")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Payment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Recyclable")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Reference")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoundMode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoundType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecureKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShippingNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalDiscounts")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalDiscountsTaxExcl")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalDiscountsTaxIncl")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalPaid")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalPaidReal")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalPaidTaxExcl")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalPaidTaxIncl")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalProducts")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalProductsWt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalShipping")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalShippingTaxExcl")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalShippingTaxIncl")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalWrapping")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalWrappingTaxExcl")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalWrappingTaxIncl")
                        .HasColumnType("TEXT");

                    b.Property<int>("Valid")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("PrestaToSap.model.OrderRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdCustomization")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductAttributeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductEan13")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductIsbn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ProductPrice")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductReference")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductUpc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UnitPriceTaxExcl")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UnitPriceTaxIncl")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderRows");
                });

            modelBuilder.Entity("PrestaToSap.model.OrderRow", b =>
                {
                    b.HasOne("PrestaToSap.model.Order", "Order")
                        .WithMany("OrderRows")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("PrestaToSap.model.Order", b =>
                {
                    b.Navigation("OrderRows");
                });
#pragma warning restore 612, 618
        }
    }
}
